### ISSUE TITLE
Dumps not available?

### ISSUE THREAD

**Issue by scriptzteam** [PXgamer/KatRevive#13]
https://mega.nz/#F!FJoBEYJL!RmsUT3NEtF7Xb0x0zFoBog

not works

**Comment by owenvoke** [comment]
Account was suspended.

Gimme a bit :+1:

**Comment by scriptzteam** [comment]
Got that file will upload on usenet ;)

**Comment by owenvoke** [comment]
Fixed in bc08e7efb5c289bf4c62e7e6db79580ff54d0799 with multiple links lol
