### ISSUE TITLE
Add moderation/editing of torrent titles and details

### ISSUE THREAD

**Issue by owenvoke** [PXgamer/KatRevive#14]
Following commit bcd95d12b864406bb5f6a0470c773eae6c124f99, will be adding the ability to edit torrent details (as currently it pulls the title from the .torrent file).

**Comment by owenvoke** [comment]
Added in commit 4451ec232378e74a52697440bca804ecde3dd785

**Comment by ScribeOfGoD** [comment]
Px is a nob
